# Yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  workflow_call:
    inputs:
      SHA:
        required: true
        type: string
      DATADOG_API_KEY:
        required: false
        type: string
        default: ''
      RUN_LINT_AND_FORMAT:
        required: false
        type: boolean
        default: false
      RUN_TYPECHECK:
        required: false
        type: boolean
        default: false
      RUN_TESTS:
        required: false
        type: boolean
        default: false
      RUN_DATADOG_UPLOAD:
        required: false
        type: boolean
        default: false

env:
  NODE_VERSION: 18
  PNPM_VERSION: 8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ inputs.SHA }}
          restore-keys: ${{ runner.os }}-turbo-

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build:ci

      - if: ${{ inputs.RUN_LINT_AND_FORMAT }}
        name: Lint & format packages
        run: pnpm lint-format

      - if: ${{ inputs.RUN_TYPECHECK }}
        name: Typecheck packages
        run: pnpm typecheck

      - if: ${{ inputs.RUN_TESTS }}
        name: Test packages
        run: pnpm test --filter='!subgraph'

      - if: ${{ inputs.RUN_DATADOG_UPLOAD }}
        name: Get git short hash
        id: get_git_short_hash
        run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - if: ${{ inputs.RUN_DATADOG_UPLOAD }}
        name: Upload sourcemap for Restake App
        run: |
          npx datadog-ci sourcemaps upload ./packages/frontend/.next/static \
          --service=rio_network_app_-_production \
          --release-version=$GITHUB_SHA \
          --minified-path-prefix=/_next/static \
          --dry-run=true \
        env:
          DATADOG_SITE: us5.datadoghq.com
          DATADOG_API_HOST: api.us5.datadoghq.com
          DATADOG_API_KEY: ${{ inputs.DATADOG_API_KEY }}
          GIT_HASH: ${{ steps.get_git_short_hash.outputs.GIT_HASH }}
