# Yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

on:
  push:
    branches: ['main']

  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build packages
    uses: ./.github/workflows/build.yaml
    with:
      sha: ${{ github.sha }}

  lint-and-format:
    needs: build
    name: Lint and format packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Load cache and/or build packages
        uses: ./.github/workflows/build.yaml
        with:
          sha: ${{ github.sha }}

      - name: Lint & format packages
        run: pnpm lint-format

  typecheck:
    needs: build
    name: Type-check packages
    runs-on: ubuntu-latest
    steps:
      - name: Load cache and/or build packages
        uses: ./.github/workflows/build.yaml
        with:
          sha: ${{ github.sha }}

      - name: Typecheck packages
        run: pnpm typecheck

  test:
    needs: build
    name: Test packages
    runs-on: ubuntu-latest
    steps:
      - name: Load cache and/or build packages
        uses: ./.github/workflows/build.yaml
        with:
          sha: ${{ github.sha }}

      - name: Test packages
        run: pnpm test --filter='!subgraph'
